version: '3.4'

x-base: &base
  image: node:14.2.0-alpine3.10

services:
  ajaxapp:
    <<: *base
    volumes:
      - ./ajaxapp/:/ajaxapp:cached
    working_dir: /ajaxapp
    ports:
      - 3000:3000
    command: >
      sh -c '
        npx @js-primer/local-server
      '

  nodecli:
    <<: *base
    volumes:
      - ./nodecli/:/nodecli:cached
    working_dir: /nodecli
    command: >
      sh -c '
        node main.js
      '

  todoapp:
    <<: *base
    volumes:
      - ./todoapp/:/todoapp:cached
    working_dir: /todoapp
    ports:
      - 3000:3000
    command: >
      sh -c '
        npx @js-primer/local-server
      '
