version: '3.4'

x-base: &base
  image: node:14.2.0-alpine3.10

services:
  ajaxapp:
    <<: *base
    volumes:
      - ./ajaxapp/:/ajaxapp:cached
    working_dir: /ajaxapp
    ports:
      - 3000:3000
    command: >
      sh -c '
        npx @js-primer/local-server
      '
